-- Tim : Henderson
-- Table : Creation : for : diplomacy

START : TRANSACTION;
USE : diplomacy;
----------------------------------------  Schema  -------------------------------------
--  users (usr_id : varchar(64), name : varchar(256), email : varchar(256), 
--          screen_name : varchar(128), pass_hash : varchar(64), salt : varchar(64),
--          last_login : datetime, creation : datetime, status : varchar(500))
--     
--  session (session_id : varchar(64), sig_id : varchar(64), msg_sig : varchar(64),
--              usr_id : varchar(64), last_update : datetime)
--     
--  message (msg_id : int(11), from_usr : varchar(64), to_usr : varchar(64),
--              time_sent : datetime, subject : varchar(256), msg : varchar(10000)
--              read : tinyint(1))
--     
--  map (map_id : int(11), world_name : varchar(128), pic : varchar(64), keep : tinyint(1))
--     
--  game (gam_id : int(11), map_id : int(11), season : enum('spring', 'fall'), year : year(4))
--     
--  country (cty_id : int(11), usr_id : varchar(64), map_id : int(11), color : varchar(8))
--     
--  territory (ter_id : int(11), map_id : int(11), name : varchar(128), abbrev : varchar(4),
--              piece_x : int(11), piece_y : int(11), label_x : int(11), label_y : int(11))
--     
--  adjacent (ter_id : int(11), adj_ter_id : int(11))
--     
--  land (ter_id : int(11), cty_id : int(11), color : varchar(8), supply : tinyint(1),
--          coastal : tinyint(1))
--     
--  sea (ter_id : int(11))
--          
--  triangle (tri_id : int(11), ter_id : int(11), x1 : int(11), y1 : int(11), x2 : int(11),
--              y2 : int(11), x3 : int(11), y3 : int(11))
--     
--  line (ln_id : int(11), x1 : int(11), y1 : int(11), x2 : int(11), y2 : int(11))
--     
--  ter_ln_relation (ter_id : int(11), ln_id : int(11))
--     
--  piece (pce_id : int(11), cty_id : int(11), ter_id : int(11), type : enum('fleet', 'army'))
--     
--  order_type (odt_id : int(11), order : varchar(128))
--     
--  order (ord_id : int(11), cty_id : int(11), pce_id : int(11), season : enum('spring', 'fall'),
--          year : year(4), order_type : int(11), destination : int(11), executed : tinyint(1))
--     
--  operands (opr_id : int(11), ord_id : int(11), ter_id : int(11))
----------------------------------------  Schema  -------------------------------------
COMMIT;